mutation createOrder($productIds: [ID!]!, $paymentType: String!) {
	createOrder(productIds: $productIds, paymentType: $paymentType) {
		order {
			id
			userId
			organizationId
			products {
				name
				price
			}
		}
		errors
	}
}
