mutation createOrder($productIds: [Int!]!, $paymentType: String!) {
	createOrder(productIds: $productIds, paymentType: $paymentType) {
		order {
			id
			createdAt
			products {
				name
				price
			}
			paymentType
			paid
		}
		errors
	}
}
