mutation register(
	$username: String!
	$firstName: String!
	$lastName: String!
	$email: String!
	$password: String!
	$passwordConfirmation: String!
	$verificationCode: String!
) {
	registerUser(
		registrationDetails: {
			username: $username
			firstName: $firstName
			lastName: $lastName
			email: $email
			password: $password
			passwordConfirmation: $passwordConfirmation
		}
		verificationCode: $verificationCode
	) {
		user {
			id
			firstName
			lastName
			username
			email
			authenticationToken
		}
		errors
	}
}
